name: dt

include:
  - services/auth/login.yaml
  - services/development/convex.yaml
  - services/development/dev.yaml
  - services/development/forgejo.yaml
  - services/development/n8n.yaml
  - services/infrastructure/traefik.yaml
  - services/infrastructure/wireguard.yaml
#  - services/media/immich.yaml
#  - services/media/jellyfin.yaml
  - services/media/plex.yaml
  - services/media/prowlarr.yaml
  - services/media/radarr.yaml
  - services/media/readarr.yaml
  - services/media/sonarr.yaml
  - services/media/transmission.yaml
  - services/utilities/heimdall.yaml
#  - services/utilities/netbootxyz.yaml
  - services/utilities/samba.yaml

volumes:
  media:

networks:
  default:
    name: dt_default
