services:
  prowlarr:
    restart: always
    image: lscr.io/linuxserver/prowlarr
    volumes:
      - prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.prowlarr.entrypoints": websecure
      "traefik.http.routers.prowlarr.rule": "Host(`prowlarr.${DOMAIN}`)"
      "traefik.http.routers.prowlarr.tls.certresolver": "default"
      traefik.http.routers.prowlarr.middlewares: login@docker

volumes:
  prowlarr:
