services:
  readarr:
    restart: always
    image: "lscr.io/linuxserver/readarr:develop"
    volumes:
      - readarr:/config
      - media:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.readarr.entrypoints": websecure
      "traefik.http.routers.readarr.rule": "Host(`readarr.${DOMAIN}`)"
      "traefik.http.routers.readarr.tls.certresolver": "default"
      traefik.http.routers.readarr.middlewares: login@docker

volumes:
  readarr:
