services:
  forgejo:
    restart: always
    image: codeberg.org/forgejo/forgejo:14
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.forgejo.entrypoints": websecure
      "traefik.http.routers.forgejo.rule": "Host(`forgejo.${DOMAIN}`)"
      "traefik.http.routers.forgejo.tls.certresolver": "default"
      "traefik.http.services.forgejo.loadbalancer.server.port": "3000"

  forgejo-runner-dind:
    image: docker:dind
    privileged: true
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    restart: unless-stopped

  forgejo-runner:
    image: data.forgejo.org/forgejo/runner:11
    depends_on:
      - forgejo-runner-dind
    environment:
      DOCKER_HOST: tcp://forgejo-runner-dind:2375
    user: "1001:1001"
    volumes:
      - forgejo-runner-data:/data
    restart: unless-stopped
    command: /bin/sh -c "sleep 5; forgejo-runner daemon --config /data/config.yml"

volumes:
  forgejo:
  forgejo-runner-data:
